version: '3.9'

services:
  api:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
